<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'DzProject\Module'                                 => __DIR__ . '/Module.php',
  'spec\DzProject\Entity\ProjectSpec'                => __DIR__ . '/spec/DzProject/Entity/ProjectSpec.php',
  'DzProject\Controller\ProjectController'           => __DIR__ . '/src/DzProject/Controller/ProjectController.php',
  'DzProject\Entity\Project'                         => __DIR__ . '/src/DzProject/Entity/Project.php',
  'DzProject\Entity\ProjectInterface'                => __DIR__ . '/src/DzProject/Entity/ProjectInterface.php',
  'DzProject\Form\Add'                               => __DIR__ . '/src/DzProject/Form/Add.php',
  'DzProject\Mapper\Project'                         => __DIR__ . '/src/DzProject/Mapper/Project.php',
  'DzProject\Mapper\ProjectInterface'                => __DIR__ . '/src/DzProject/Mapper/ProjectInterface.php',
  'DzProject\Options\ModuleOptions'                  => __DIR__ . '/src/DzProject/Options/ModuleOptions.php',
  'DzProject\Options\ProjectServiceOptionsInterface' => __DIR__ . '/src/DzProject/Options/ProjectServiceOptionsInterface.php',
  'DzProject\Service\Project'                        => __DIR__ . '/src/DzProject/Service/Project.php',
  'Codeception\Module\CodeHelper'                    => __DIR__ . '/tests/_helpers/CodeHelper.php',
  'Codeception\Module\TestHelper'                    => __DIR__ . '/tests/_helpers/TestHelper.php',
  'Codeception\Module\WebHelper'                     => __DIR__ . '/tests/_helpers/WebHelper.php',
  'WebGuy'                                           => __DIR__ . '/tests/acceptance/WebGuy.php',
  'TestGuy'                                          => __DIR__ . '/tests/functional/TestGuy.php',
  'CodeGuy'                                          => __DIR__ . '/tests/unit/CodeGuy.php',
);
