<?php

/**
 * Vue pour l'action ProjectController::addAction()
 * Ajout d'un nouveau projet
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProjectModule
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link       https://github.com/dieze/DzProjectModule
 */

?>

<?php

$this->setHeadTitle("Ajout d'un projet");
echo $this->renderTitle("Ajout d'un projet");
//echo $this->renderDatePickerJs();

echo $this->renderFormOpenTag();

?>

	<fieldset>

	    <?php

	    echo $this->renderFormGroup('displayName');
	    echo $this->renderFormGroup('beginDate');
	    echo $this->renderFormGroup('endDate');

	    echo $this->renderRedirectSuccess();
	    echo $this->renderRedirectFailure();
	    echo $this->renderHiddenElements();
	    echo $this->renderSubmit();

	    ?>
	    
	</fieldset>
    
</form>