<?php

/**
 * Vue pour l'action ProjectController::deleteAction()
 * Suppression d'un projet
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProjectModule
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link       https://github.com/dieze/DzProjectModule
 */

?>

<?php

$project     = $this->project;
$displayName = $project['display_name'];

$this->setHeadTitle("Suppression d'un projet");
echo $this->renderTitle("Suppression d'un projet");

echo $this->renderFormOpenTag();

?>

<p>
	Voulez-vous vraiment supprimer le projet
	
	<?php
	echo $displayName;
	?>

	?
</p>

<?php

echo $this->renderRedirect();
echo $this->renderSubmit();

?>
</form>