<?php

/**
 * Vue pour l'action ProjectController::addAction()
 * Ajout d'un nouveau projet
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProject
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzProject/blob/master/view/dz-project/project/add.phtml
 */

?>

<?php $this->inlineScript()->captureStart(); ?>
Modernizr.load({
    test: Modernizr.inputtypes.date,
    nope: [
        'http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js',
        'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.7/jquery-ui.min.js'
    ],
    complete: function () {
        $('input[type=date]').datepicker({
            dateFormat: 'dd/mm/yy'
        });
    }
});
<?php $this->inlineScript()->captureEnd(); ?>

<h1>Ajout d'un projet</h1>

<?php
$form = $this->addForm;
$form->prepare();
$form->setAttribute('action', $this->url('dzproject/add'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend_form">
        <?php echo $this->formElementErrors($form->get('displayName')) ?>

        <dt><?php echo $this->formLabel($form->get('displayName')) ?></dt>
        <dd><?php echo $this->formInput($form->get('displayName')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('beginDate')) ?></dt>
        <dd><?php echo $this->formInput($form->get('beginDate')) ?></dd>

        <dt><?php echo $this->formLabel($form->get('endDate')) ?></dt>
        <dd><?php echo $this->formInput($form->get('endDate')) ?></dd>

        <?php
        if ($this->redirect) :
            ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php
        endif
        ?>

        <dd><?php echo $this->formButton($form->get('add')) ?></dd>
    </dl>

<?php echo $this->form()->closeTag() ?>
