<?php

/**
 * Vue pour le widget DzProjectAddWidget
 * Ajout d'un nouveau projet
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProject
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzProject/blob/master/view/dz-project/project/addWidget.phtml
 */

?>

<?php echo $this->render('dz-project/project/add.phtml');