<?php

/**
 * Vue pour l'action ProjectController::deleteAction()
 * Suppression d'un projet
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProject
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzProject/blob/master/view/dz-project/project/delete.phtml
 */

?>

<?php $p = $this->project; ?>

<?php
// Titre affiché ou non
if (isset($this->hasTitle) && !$this->hasTitle) {
} else {
    ?>
<h1>Suppression d'un projet</h1>
    <?php
} ?>

<form method="post" action="<?php echo $this->url('dzproject/delete', array('id' => $p['project_id'])); ?>">

    <p>Voulez vous vraiment supprimer le projet <?php echo $p['display_name']; ?> ?</p>

    <?php
    // Redirection ou non
    if ($this->redirect) :
        ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php
    endif
    ?>

    <?php
    // Bouton d'envoi du formulaire affiché ou non
    if (isset($this->hasSubmit) && !$this->hasSubmit) {
    } else {
        ?>
    <input type="submit" name="submit" value="Supprimer" class="btn btn-danger"/>
    	<?php
    } ?>
</form>
