<?php

/**
 * Vue pour l'action ProjectController::listAction()
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProject
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzProject/blob/master/view/dz-project/project/list.phtml
 */

?>

<?php $this->headTitle('Liste des projets'); ?>

<?php
// Affiche le formulaire d'ajout au chargement
// de la page si il y a des erreurs de validation
if ($this->addForm->getMessages()) {
    $this->inlineScript()->captureStart();
    ?>
$('#addProjectModal').modal('show');
    <?php
    $this->inlineScript()->captureEnd();
}
?>

<?php
// Titre affiché ou non
if (isset($this->hasTitle) && !$this->hasTitle) {
} else {
    ?>
<h1>Liste des projets</h1>
    <?php
} ?>

<?php
// Bouton d'ajout de projet affiché ou non
if ($this->hasAddAction) {
    ?>
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addProjectModal">Add</button>

<div class="modal" id="addProjectModal" tabindex="-1" role="dialog" aria-labelledby="addProjectModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="addProjectModalLabel">Ajout d'un projet</h4>
            </div>
            <div class="modal-body">
                <?php
                echo $this->dzProjectAddWidget(
                    array(
                        'hasTitle' => false,
                        'hasSubmit' => false,
                        'redirectSuccess' => $this->currentUrl(),
                        'redirectFailure' => $this->currentUrl(),
                    )
                );
                ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="$('#addProjectModal form').submit()">Nouveau</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>
    <?php
} ?>

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <?php
                // Bouton de suppression de projet affiché ou non (heading)
                if ($this->hasDeleteAction) {
                    ?>
                <th></th>
                    <?php
                } ?>

                <?php
                // Champs du tableau (headings)
                foreach ($this->fields as $field) {
                    echo '<th class="heading">' . $field['heading'] . '</th>';
                }
                ?>
            </tr>
        </thead>
        <tbody>
        <?php
        // Listing projets
        foreach ($this->projects as $p) {
            ?>
            <tr class="entry">
            <?php
            // Bouton de suppression du projet affiché ou non (bouton)
            if ($this->hasDeleteAction) {
                ?>
                <td>
                    <button class="btn btn-default action" data-toggle="modal" data-target="#deleteProjectModal<?php echo $p['project_id']; ?>"><img src="/img/DzProject/trash.png" alt="Delete" class="deleteAction"/></button>
                </td>
                <?php
            } ?>

            <?php
            // Champs du tableau (cellules)
            foreach ($this->fields as $field) {
                
                // href: lien de la cellule
                if (isset($field['href']) && isset($field['href'][$p['project_id']])) {
                    $href = $field['href'][$p['project_id']];
                } else {
                    $href = false;
                }

                // value: valeur de la cellule
                if (isset($field['values']) && isset($field['values'][$p['project_id']])) {
                    $value = $field['values'][$p['project_id']];
                } else {
                    $value = false;
                }

                // class: attribut class de la cellule
                if (isset($field['class']) && isset($field['class'][$p['project_id']])) {
                    $class = $field['class'][$p['project_id']];
                } else {
                    $class = false;
                }

                // Ouverture de cellule
                if ($class) {
                    ?>
                <td class="<?php echo $class; ?>">
                    <?php
                } else {
                    ?>
                <td>
                    <?php
                }

                if ($href) {
                    ?>
                <a href="<?php echo $href; ?>" class="href">
                    <?php
                }

                // Valeur de cellule.
                // Attention! Peut valoir 0 ou 'false'
                if ($value !== false) {
                    ?>
                    <span class="value"><?php echo $value; ?></span>
                    <?php
                }

                // Lien de cellule (balise de fermeture)
                if ($href) {
                    ?>
                </a>
                    <?php
                } ?>
            </td>
                <?php
            }
            ?>
        </tr>
            <?php
        }
        ?>
        </tbody>
    </table>
</div>

<?php
// Fenêtres Modal Bootstrap de suppression des projets
if ($this->hasDeleteAction) {
    foreach ($projects as $p) {
        ?>
<div class="modal fade" id="deleteProjectModal<?php echo $p['project_id']; ?>" tabindex="-1" role="dialog" aria-labelledby="deleteProjectModalLabel<?php echo $p['project_id']; ?>" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                 <h4 class="modal-title" id="deleteProjectModalLabel<?php echo $p['project_id']; ?>">Supprimer un projet</h4>
            </div>
            <div class="modal-body">
                <?php
                echo $this->dzProjectDeleteWidget($p['project_id'],
                    array(
                        'hasTitle' => false,
                        'hasSubmit' => false
                    )
                );
                ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" onclick="$('#deleteProjectModal<?php echo $p['project_id']; ?> form').submit()">Supprimer</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>
        <?php
    }
} ?>
