<?php

/**
 * Vue pour l'aide de vue DzProjectShowAllWidget
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProject
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzProject/blob/master/view/dz-project/project/showallWidget.phtml
 */

?>

<?php echo $this->render('dz-project/project/showall.phtml'); ?>