<?php

/**
 * Vue pour l'action ProjectController::showallAction()
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProject
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 * @link       https://github.com/dieze/DzProject/blob/master/view/dz-project/project/showall.phtml
 */

?>

<h1>Projets</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Période</th>
    </tr>
  </thead>
  <tbody>
<?php
foreach ($projects as $p) {
    ?>
    <tr>
      <td><?php echo $p->getDisplayName(); ?></td>
      <td><?php echo strftime("%d/%m/%Y", $p->getBeginDate()) . ' - ' . strftime("%d/%m/%Y", $p->getEndDate()); ?></td>
    </tr>
    <?php
}
?>
  </tbody>
</table>
