<?php

/**
 * ProjectController::showallAction() view source
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @package    DzProject
 * @subpackage View
 * @category   Source
 * @license    http://opensource.org/licenses/GPL-2.0 GNU General Public License, version 2
 */

?>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Period</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($projects as $p) { ?>
    <tr>
      <td><?php echo $p->getDisplayName(); ?></td>
      <td><?php echo strftime("%d/%m/%Y", $p->getBeginDate()) . ' - ' . strftime("%d/%m/%Y", $p->getEndDate()); ?></td>
    </tr>
    <?php } ?>
  </tbody>
</table>
