<?php

/**
 * Vue pour le layout
 *
 * PHP version 5
 *
 * @category   Source
 * @package    DzProjectModule
 * @subpackage View
 * @author     Adrien Desfourneaux (aka Dieze) <dieze51@gmail.com>
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 * @link       https://github.com/dieze/DzProjectModule
 */

?>

<?php

$routeName   = $this->routeName();
$page = '';

switch ($routeName)
{
    case 'dzproject':
        $page = 'info';
        break;

    case 'dzproject/add':
        $page = 'add';
        break;

    case 'dzproject/delete':
        $page = 'delete';
        break;

    case 'dzproject/list':
        $type = $this->routeParam('type');
        $page = 'list-' . $type;
        break;
}

?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('DzProjectModule')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php
echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Link -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>

<!-- Script -->
<?php echo $this->headScript(); ?>

<!-- Style -->
<?php echo $this->headStyle(); ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('dzproject') ?>">DzProjectModule</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        
                        <li<?php if ($page == 'info') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dzproject') ?>">Informations du module</a>
                        </li>

                        <li<?php if ($page == 'add') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dzproject/add') ?>">Ajouter un projet</a>
                        </li>

                        <li<?php if ($page == 'delete') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dzproject/delete', array('id' => '1')) ?>">Supprimer un projet</a>
                        </li>

                        <li<?php if ($page == 'list-all') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dzproject/list', array('type' => 'all')) ?>">Lister tous les projets</a>
                        </li>

                        <li<?php if ($page == 'list-active') : ?> class="active"<?php endif ?>>
                            <a href="<?php echo $this->url('dzproject/list', array('type' => 'active')) ?>">Lister les projets actifs</a>
                        </li>

                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
